-- Permanent rewards use canonical Shikimori IDs, as history.anime_id does.
-- Existing Plus pins and all earned cosmetics keep their access rules.
INSERT INTO achievements(id,slug,name,description,category,metric,threshold,anime_id,sort_order) VALUES ('achievement:naruto','naruto','Путь шиноби','Посмотри 50 серий «Наруто»','anime','anime_completed_episodes',50,20,100) ON CONFLICT DO NOTHING;
INSERT INTO cosmetics(id,kind,slug,name,description,rarity,image,access_type,sort_order,created_at) VALUES ('pin:achievement-naruto','pin','achievement-naruto','Повязка Конохи','Посмотри 50 серий «Наруто». Пин остаётся навсегда.','epic','/pins/achievement-naruto.svg','achievement',300,0) ON CONFLICT DO NOTHING;
INSERT INTO achievement_rewards VALUES ('achievement:naruto','pin:achievement-naruto') ON CONFLICT DO NOTHING;
INSERT INTO achievements(id,slug,name,description,category,metric,threshold,anime_id,sort_order) VALUES ('achievement:bleach','bleach','Пробуждение синигами','Посмотри 50 серий «Блич»','anime','anime_completed_episodes',50,269,101) ON CONFLICT DO NOTHING;
INSERT INTO cosmetics(id,kind,slug,name,description,rarity,image,access_type,sort_order,created_at) VALUES ('pin:achievement-bleach','pin','achievement-bleach','Клинок синигами','Посмотри 50 серий «Блич». Пин остаётся навсегда.','epic','/pins/achievement-bleach.svg','achievement',301,0) ON CONFLICT DO NOTHING;
INSERT INTO achievement_rewards VALUES ('achievement:bleach','pin:achievement-bleach') ON CONFLICT DO NOTHING;
INSERT INTO achievements(id,slug,name,description,category,metric,threshold,anime_id,sort_order) VALUES ('achievement:death-note','death-note','Последняя запись','Посмотри 37 серий «Тетрадь смерти»','anime','anime_completed_episodes',37,1535,102) ON CONFLICT DO NOTHING;
INSERT INTO cosmetics(id,kind,slug,name,description,rarity,image,access_type,sort_order,created_at) VALUES ('pin:achievement-death-note','pin','achievement-death-note','Запретная тетрадь','Посмотри 37 серий «Тетрадь смерти». Пин остаётся навсегда.','legendary','/pins/achievement-death-note.svg','achievement',302,0) ON CONFLICT DO NOTHING;
INSERT INTO achievement_rewards VALUES ('achievement:death-note','pin:achievement-death-note') ON CONFLICT DO NOTHING;
INSERT INTO achievements(id,slug,name,description,category,metric,threshold,anime_id,sort_order) VALUES ('achievement:attack-on-titan','attack-on-titan','За стенами','Посмотри 25 серий «Атака титанов · сезон 1»','anime','anime_completed_episodes',25,16498,103) ON CONFLICT DO NOTHING;
INSERT INTO cosmetics(id,kind,slug,name,description,rarity,image,access_type,sort_order,created_at) VALUES ('pin:achievement-attack-on-titan','pin','achievement-attack-on-titan','Крылья разведчика','Посмотри 25 серий «Атака титанов · сезон 1». Пин остаётся навсегда.','epic','/pins/achievement-attack-on-titan.svg','achievement',303,0) ON CONFLICT DO NOTHING;
INSERT INTO achievement_rewards VALUES ('achievement:attack-on-titan','pin:achievement-attack-on-titan') ON CONFLICT DO NOTHING;
INSERT INTO achievements(id,slug,name,description,category,metric,threshold,anime_id,sort_order) VALUES ('achievement:demon-slayer','demon-slayer','Дыхание солнца','Посмотри 26 серий «Клинок, рассекающий демонов · сезон 1»','anime','anime_completed_episodes',26,38000,104) ON CONFLICT DO NOTHING;
INSERT INTO cosmetics(id,kind,slug,name,description,rarity,image,access_type,sort_order,created_at) VALUES ('pin:achievement-demon-slayer','pin','achievement-demon-slayer','Печать пламени','Посмотри 26 серий «Клинок, рассекающий демонов · сезон 1». Пин остаётся навсегда.','epic','/pins/achievement-demon-slayer.svg','achievement',304,0) ON CONFLICT DO NOTHING;
INSERT INTO achievement_rewards VALUES ('achievement:demon-slayer','pin:achievement-demon-slayer') ON CONFLICT DO NOTHING;
INSERT INTO achievements(id,slug,name,description,category,metric,threshold,anime_id,sort_order) VALUES ('achievement:jujutsu-kaisen','jujutsu-kaisen','За гранью проклятий','Посмотри 24 серий «Магическая битва · сезон 1»','anime','anime_completed_episodes',24,40748,105) ON CONFLICT DO NOTHING;
INSERT INTO cosmetics(id,kind,slug,name,description,rarity,image,access_type,sort_order,created_at) VALUES ('pin:achievement-jujutsu-kaisen','pin','achievement-jujutsu-kaisen','Бесконечность','Посмотри 24 серий «Магическая битва · сезон 1». Пин остаётся навсегда.','epic','/pins/achievement-jujutsu-kaisen.svg','achievement',305,0) ON CONFLICT DO NOTHING;
INSERT INTO achievement_rewards VALUES ('achievement:jujutsu-kaisen','pin:achievement-jujutsu-kaisen') ON CONFLICT DO NOTHING;
INSERT INTO achievements(id,slug,name,description,category,metric,threshold,anime_id,sort_order) VALUES ('achievement:frieren','frieren','После конца путешествия','Посмотри 28 серий «Провожающая в последний путь Фрирен · сезон 1»','anime','anime_completed_episodes',28,52991,106) ON CONFLICT DO NOTHING;
INSERT INTO cosmetics(id,kind,slug,name,description,rarity,image,access_type,sort_order,created_at) VALUES ('pin:achievement-frieren','pin','achievement-frieren','Кристалл вечности','Посмотри 28 серий «Провожающая в последний путь Фрирен · сезон 1». Пин остаётся навсегда.','legendary','/pins/achievement-frieren.svg','achievement',306,0) ON CONFLICT DO NOTHING;
INSERT INTO achievement_rewards VALUES ('achievement:frieren','pin:achievement-frieren') ON CONFLICT DO NOTHING;
INSERT INTO achievements(id,slug,name,description,category,metric,threshold,anime_id,sort_order) VALUES ('achievement:chainsaw-man','chainsaw-man','Сердце демона','Посмотри 12 серий «Человек-бензопила · сезон 1»','anime','anime_completed_episodes',12,44511,107) ON CONFLICT DO NOTHING;
INSERT INTO cosmetics(id,kind,slug,name,description,rarity,image,access_type,sort_order,created_at) VALUES ('pin:achievement-chainsaw-man','pin','achievement-chainsaw-man','Сердце бензопилы','Посмотри 12 серий «Человек-бензопила · сезон 1». Пин остаётся навсегда.','epic','/pins/achievement-chainsaw-man.svg','achievement',307,0) ON CONFLICT DO NOTHING;
INSERT INTO achievement_rewards VALUES ('achievement:chainsaw-man','pin:achievement-chainsaw-man') ON CONFLICT DO NOTHING;
INSERT INTO achievements(id,slug,name,description,category,metric,threshold,anime_id,sort_order) VALUES ('achievement:hunter-x-hunter','hunter-x-hunter','Лицензия получена','Посмотри 50 серий «Охотник × Охотник (2011)»','anime','anime_completed_episodes',50,11061,108) ON CONFLICT DO NOTHING;
INSERT INTO cosmetics(id,kind,slug,name,description,rarity,image,access_type,sort_order,created_at) VALUES ('pin:achievement-hunter-x-hunter','pin','achievement-hunter-x-hunter','Лицензия охотника','Посмотри 50 серий «Охотник × Охотник (2011)». Пин остаётся навсегда.','epic','/pins/achievement-hunter-x-hunter.svg','achievement',308,0) ON CONFLICT DO NOTHING;
INSERT INTO achievement_rewards VALUES ('achievement:hunter-x-hunter','pin:achievement-hunter-x-hunter') ON CONFLICT DO NOTHING;
INSERT INTO achievements(id,slug,name,description,category,metric,threshold,anime_id,sort_order) VALUES ('achievement:fullmetal-alchemist','fullmetal-alchemist','Равноценный обмен','Посмотри 64 серий «Стальной алхимик: Братство»','anime','anime_completed_episodes',64,5114,109) ON CONFLICT DO NOTHING;
INSERT INTO cosmetics(id,kind,slug,name,description,rarity,image,access_type,sort_order,created_at) VALUES ('pin:achievement-fullmetal-alchemist','pin','achievement-fullmetal-alchemist','Печать алхимика','Посмотри 64 серий «Стальной алхимик: Братство». Пин остаётся навсегда.','legendary','/pins/achievement-fullmetal-alchemist.svg','achievement',309,0) ON CONFLICT DO NOTHING;
INSERT INTO achievement_rewards VALUES ('achievement:fullmetal-alchemist','pin:achievement-fullmetal-alchemist') ON CONFLICT DO NOTHING;
INSERT INTO cosmetics(id,kind,slug,name,description,rarity,image,access_type,sort_order,created_at) VALUES ('pin:achievement-one-piece','pin','achievement-one-piece','Сокровище Мугивары','Посмотри 100 серий One Piece. Пин остаётся навсегда.','epic','/pins/achievement-one-piece.svg','achievement',299,0) ON CONFLICT DO NOTHING;
INSERT INTO achievement_rewards VALUES ('achievement:one-piece-100','pin:achievement-one-piece') ON CONFLICT DO NOTHING;
INSERT INTO cosmetics(id,kind,slug,name,description,rarity,style_json,access_type,sort_order,created_at) VALUES ('frame:referral-bloom','frame','referral-bloom','Сакура дружбы','За 1 приглашённых друзей, посмотревших по 60 минут аниме.','rare','{"class":"referral-bloom","animated":true}','referral',201,0) ON CONFLICT DO NOTHING;
INSERT INTO cosmetics(id,kind,slug,name,description,rarity,style_json,access_type,sort_order,created_at) VALUES ('frame:referral-wings','frame','referral-wings','Крылья искателя','За 3 приглашённых друзей, посмотревших по 60 минут аниме.','epic','{"class":"referral-wings","animated":true}','referral',203,0) ON CONFLICT DO NOTHING;
INSERT INTO cosmetics(id,kind,slug,name,description,rarity,style_json,access_type,sort_order,created_at) VALUES ('frame:referral-tide','frame','referral-tide','Волна накама','За 5 приглашённых друзей, посмотревших по 60 минут аниме.','epic','{"class":"referral-tide","animated":true}','referral',205,0) ON CONFLICT DO NOTHING;
INSERT INTO cosmetics(id,kind,slug,name,description,rarity,style_json,access_type,sort_order,created_at) VALUES ('frame:referral-phoenix','frame','referral-phoenix','Огненный феникс','За 25 приглашённых друзей, посмотревших по 60 минут аниме.','legendary','{"class":"referral-phoenix","animated":true}','referral',225,0) ON CONFLICT DO NOTHING;
INSERT INTO user_cosmetics(user_id,cosmetic_id,unlocked_at,source,source_key,metadata)
SELECT ua.user_id,ar.cosmetic_id,ua.unlocked_at,'achievement',ua.achievement_id || ':' || c.slug,jsonb_build_object('achievement',a.slug)
FROM user_achievements ua JOIN achievement_rewards ar ON ar.achievement_id=ua.achievement_id
JOIN cosmetics c ON c.id=ar.cosmetic_id JOIN achievements a ON a.id=ua.achievement_id
WHERE c.slug='achievement-one-piece' ON CONFLICT DO NOTHING;
INSERT INTO user_cosmetics(user_id,cosmetic_id,unlocked_at,source,source_key,metadata)
SELECT r.referrer_id,'frame:' || reward.slug,(extract(epoch FROM clock_timestamp())*1000)::bigint,
'referral','referral:' || reward.threshold || ':' || reward.slug,jsonb_build_object('milestone',reward.threshold)
FROM referrals r CROSS JOIN (VALUES ('referral-bloom',1),('referral-wings',3),('referral-tide',5),('referral-phoenix',25)) reward(slug,threshold)
WHERE r.status='qualified' GROUP BY r.referrer_id,reward.slug,reward.threshold
HAVING count(*)>=reward.threshold ON CONFLICT DO NOTHING;
