-- Frames for subscribers and anime achievements.
INSERT INTO cosmetics(id,kind,slug,name,description,rarity,style_json,access_type,sort_order,created_at) VALUES ('frame:plus-sakura','frame','plus-sakura','Цветение сакуры','Доступна с активной подпиской AniMonster Plus.','epic','{"class":"plus-sakura","animated":true}','plus',300,0) ON CONFLICT DO NOTHING;
INSERT INTO cosmetics(id,kind,slug,name,description,rarity,style_json,access_type,sort_order,created_at) VALUES ('frame:plus-illusion','frame','plus-illusion','Иллюзия','Доступна с активной подпиской AniMonster Plus.','epic','{"class":"plus-illusion","animated":true}','plus',301,0) ON CONFLICT DO NOTHING;
INSERT INTO cosmetics(id,kind,slug,name,description,rarity,style_json,access_type,sort_order,created_at) VALUES ('frame:plus-crystal','frame','plus-crystal','Кристальная мантия','Доступна с активной подпиской AniMonster Plus.','epic','{"class":"plus-crystal","animated":true}','plus',302,0) ON CONFLICT DO NOTHING;
INSERT INTO cosmetics(id,kind,slug,name,description,rarity,style_json,access_type,sort_order,created_at) VALUES ('frame:achievement-shinobi','frame','achievement-shinobi','Наследие шиноби','Посмотри 50 серий «Наруто». Рамка остаётся навсегда.','legendary','{"class":"achievement-shinobi","animated":true}','achievement',303,0) ON CONFLICT DO NOTHING;
INSERT INTO achievement_rewards VALUES ('achievement:naruto','frame:achievement-shinobi') ON CONFLICT DO NOTHING;
INSERT INTO cosmetics(id,kind,slug,name,description,rarity,style_json,access_type,sort_order,created_at) VALUES ('frame:achievement-scout','frame','achievement-scout','За свободу','Посмотри 25 серий «Атака титанов · сезон 1». Рамка остаётся навсегда.','legendary','{"class":"achievement-scout","animated":true}','achievement',304,0) ON CONFLICT DO NOTHING;
INSERT INTO achievement_rewards VALUES ('achievement:attack-on-titan','frame:achievement-scout') ON CONFLICT DO NOTHING;
INSERT INTO cosmetics(id,kind,slug,name,description,rarity,style_json,access_type,sort_order,created_at) VALUES ('frame:achievement-oni','frame','achievement-oni','Oni','Посмотри 26 серий «Клинок, рассекающий демонов · сезон 1». Рамка остаётся навсегда.','legendary','{"class":"achievement-oni","animated":true}','achievement',305,0) ON CONFLICT DO NOTHING;
INSERT INTO achievement_rewards VALUES ('achievement:demon-slayer','frame:achievement-oni') ON CONFLICT DO NOTHING;
INSERT INTO cosmetics(id,kind,slug,name,description,rarity,style_json,access_type,sort_order,created_at) VALUES ('frame:achievement-mage','frame','achievement-mage','Магия вечности','Посмотри 28 серий «Провожающая в последний путь Фрирен · сезон 1». Рамка остаётся навсегда.','legendary','{"class":"achievement-mage","animated":true}','achievement',306,0) ON CONFLICT DO NOTHING;
INSERT INTO achievement_rewards VALUES ('achievement:frieren','frame:achievement-mage') ON CONFLICT DO NOTHING;
INSERT INTO cosmetics(id,kind,slug,name,description,rarity,style_json,access_type,sort_order,created_at) VALUES ('frame:achievement-alchemist','frame','achievement-alchemist','Круг преобразования','Посмотри 64 серий «Стальной алхимик: Братство». Рамка остаётся навсегда.','legendary','{"class":"achievement-alchemist","animated":true}','achievement',307,0) ON CONFLICT DO NOTHING;
INSERT INTO achievement_rewards VALUES ('achievement:fullmetal-alchemist','frame:achievement-alchemist') ON CONFLICT DO NOTHING;
