'use client';
import { useEffect, useState } from 'react';
import { Search, Play, Bookmark, ArrowUpRight, Sparkles, Ghost, ChevronRight, Shuffle, Check, Film } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import initial from './catalog.json';
type Anime = {id:number;name:string;russian:string;image:{original:string};score:string;kind:string;episodes:number;aired_on:string};
type Video = {id:number;name:string;url:string;player_url:string};
const seed = (initial as Anime[]).filter(a=>!a.image.original.includes('missing'));
export default function Home(){
 const [items,setItems]=useState<Anime[]>(seed),[query,setQuery]=useState(''),[tab,setTab]=useState('all'),[saved,setSaved]=useState<Anime[]>([]),[active,setActive]=useState<Anime|null>(null),[videos,setVideos]=useState<Video[]>([]),[video,setVideo]=useState<Video|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[apiStatus,setApiStatus]=useState('');
 useEffect(()=>{try{setSaved(JSON.parse(localStorage.getItem('animonster-list')||'[]'));}catch{}},[]);
 useEffect(()=>{if(tab==='saved')return;const controller=new AbortController();const timer=setTimeout(async()=>{setApiStatus('Обновляем каталог…');try{const r=await fetch('/api/catalog?q='+encodeURIComponent(query)+'&kind='+(tab==='movies'?'movie':''),{signal:controller.signal});if(!r.ok)throw Error();setItems(await r.json());setApiStatus('');}catch{if(!controller.signal.aborted)setApiStatus('API временно недоступен. Показываем сохранённый каталог.');}},400);return()=>{clearTimeout(timer);controller.abort();};},[query,tab]);
 function has(id:number){return saved.some(a=>a.id===id)}
 function toggle(a:Anime){const next=has(a.id)?saved.filter(x=>x.id!==a.id):[...saved,a];setSaved(next);try{localStorage.setItem('animonster-list',JSON.stringify(next));}catch{}}
 async function open(a:Anime){setActive(a);setVideo(null);setVideos([]);setError('');setLoading(true);try{const r=await fetch('/api/videos?id='+a.id);if(!r.ok)throw Error();const data:Video[]=await r.json();setVideos(data);setVideo(data[0]||null);}catch{setError('Видео не загрузились. Попробуйте открыть карточку ещё раз.');}finally{setLoading(false);}}
 const shown=(tab==='saved'?saved:items).filter(a=>(tab!=='movies'||a.kind==='movie')&&(!query||[a.name,a.russian].join(' ').toLowerCase().includes(query.toLowerCase())));
 return <div className="site"><header className="header"><a className="brand" href="/" aria-label="AniMonster — главная"><Ghost size={30} fill="currentColor" strokeWidth={1.7}/><span>Ani<span>Monster</span></span></a><nav><a href="#catalog">Каталог</a><button onClick={()=>{setTab('movies');document.getElementById('catalog')?.scrollIntoView({behavior:'smooth'});}}>Фильмы</button><button onClick={()=>{setTab('saved');document.getElementById('catalog')?.scrollIntoView({behavior:'smooth'});}}>Мой список <span className="count">{saved.length}</span></button></nav><button className="random" onClick={()=>open(seed[Math.floor(Math.random()*seed.length)])}><Shuffle size={17}/><span>Случайное аниме</span></button></header>
 <main><section className="hero"><img src="/hero.png" alt="Сереброволосая странница в ночной долине"/><div className="hero-shade"/><div className="hero-copy"><div className="eyebrow"><span/> ТВОЯ ТЕРРИТОРИЯ АНИМЕ</div><h1>Ещё одна серия.<br/><em>Ещё один мир.</em></h1><p>Большие приключения, тихие истории и герои,<br className="desktop"/> которые остаются с тобой.</p><div className="hero-buttons"><a className="primary" href="#catalog"><Play size={18} fill="currentColor"/> Найти своё аниме</a><button className="circle" onClick={()=>open(seed[Math.floor(Math.random()*seed.length)])} aria-label="Выбрать случайное аниме"><Shuffle size={20}/></button></div><div className="hero-meta"><span>Открой новую историю</span><i/> Собери свою коллекцию</div></div><div className="hero-corner">ANIMONSTER ORIGINAL ART <span>01 / 01</span></div></section>
 <section id="catalog" className="catalog"><div className="section-head"><div><div className="eyebrow small">ВЫБИРАЙ СВОЙ СЛЕДУЮЩИЙ МИР</div><h2>{tab==='saved'?'Мой список':'Стоит посмотреть'}<span className="lime">.</span></h2></div><label className="search"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Название аниме…" aria-label="Поиск аниме"/>{query&&<button onClick={()=>setQuery('')} aria-label="Очистить поиск">×</button>}</label></div>
 <div className="filter-row"><Tabs value={tab} onValueChange={v=>setTab(String(v))}><TabsList className="catalog-tabs"><TabsTrigger value="all">Все аниме</TabsTrigger><TabsTrigger value="movies">Полнометражные</TabsTrigger><TabsTrigger value="saved"><Bookmark size={14}/> Мой список</TabsTrigger></TabsList></Tabs><span className="catalog-meta">{shown.length} тайтлов <span>·</span> Shikimori</span></div><p className="status" role="status">{apiStatus}</p>
 <div className="cards">{shown.map((a,i)=><article className="card" key={a.id}><button className="poster" onClick={()=>open(a)} aria-label={'Открыть '+a.russian}><img src={'https://shikimori.one'+a.image.original} alt={a.russian} loading={i<6?'eager':'lazy'}/><span className="score">★ {a.score}</span><span className="poster-play"><Play fill="currentColor" size={23}/></span><span className="poster-bottom">{a.kind==='movie'?'ФИЛЬМ':`${a.episodes||'—'} СЕРИЙ`}<ChevronRight size={17}/></span></button><div className="card-title"><button onClick={()=>open(a)}>{a.russian||a.name}</button><button className={has(a.id)?'saved':''} onClick={()=>toggle(a)} aria-label={has(a.id)?'Убрать из списка':'Добавить в список'}>{has(a.id)?<Check size={18}/>:<Bookmark size={18}/>}</button></div><p>{a.aired_on?.slice(0,4)||'—'} <span>•</span> {a.kind==='movie'?'Полнометражный фильм':'ТВ-сериал'}</p></article>)}</div>
 {!shown.length&&<div className="empty"><Film size={30}/><h3>{tab==='saved'?'Здесь начинается твоя коллекция':'Ничего не нашлось'}</h3><p>{tab==='saved'?'Нажми на закладку рядом с названием аниме.':'Попробуй другое название или открой все аниме.'}</p><button className="primary" onClick={()=>{setQuery('');setTab('all');}}>Открыть каталог</button></div>}
 </section><section className="collection"><div className="collection-icon"><Sparkles size={28}/></div><div><span className="eyebrow small">НЕ ЗНАЕШЬ, ЧТО ВЫБРАТЬ?</span><h2>Позволь случаю решить.</h2><p>Иногда любимая история начинается с одного клика.</p></div><button onClick={()=>open(seed[Math.floor(Math.random()*seed.length)])}>Удиви меня <ArrowUpRight size={20}/></button></section></main>
 <footer><a className="brand" href="/">Ani<span>Monster</span></a><p>Каталог и видео — <a href="https://shikimori.one" target="_blank" rel="noreferrer">Shikimori API</a>. Доступны проморолики и трейлеры. Полные серии пока не подключены.</p><span>Сделано для тех, кто любит аниме.</span></footer>
 <Dialog open={!!active} onOpenChange={v=>{if(!v){setActive(null);setVideo(null);}}}><DialogContent className="anime-dialog">{active&&<><div className="dialog-top"><span className="eyebrow small">ANIMONSTER / ПРОСМОТР</span><DialogTitle className="dialog-title">{active.russian}</DialogTitle><DialogDescription>{active.name} · {active.episodes||'—'} серий · ★ {active.score}</DialogDescription></div><div className="player">{loading?<p>Загружаем видео…</p>:error?<p role="alert">{error}</p>:video?<iframe key={video.id} src={video.player_url.replace('http:','https:')} title={video.name||'Видео аниме'} allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowFullScreen/>:<p>У этого тайтла пока нет доступных видео.</p>}</div><div className="video-list">{videos.map(v=><button className={video?.id===v.id?'chosen':''} key={v.id} onClick={()=>setVideo(v)}><Play size={14}/>{v.name||'Трейлер'}</button>)}</div><div className="dialog-bottom"><button className="primary" onClick={()=>toggle(active)}>{has(active.id)?<Check size={17}/>:<Bookmark size={17}/>} {has(active.id)?'В моём списке':'Буду смотреть'}</button>{video&&<a href={video.url} target="_blank" rel="noreferrer">Открыть видео отдельно ↗</a>}</div><p className="notice">Трейлеры и проморолики из Shikimori API. Полные серии пока не подключены.</p></>}</DialogContent></Dialog>
 </div>
}
