export const referralMilestones = [
  {
    count: 1,
    title: 'Вербовщик',
    detail: 'Тег и рамка «Сакура дружбы»',
    frame: 'referral-bloom',
    pin: null,
    cosmetics: ['recruiter', 'referral-bloom'],
    plusDays: 0,
  },
  {
    count: 3,
    title: 'Искатель',
    detail: 'Пин-компас и рамка «Крылья искателя»',
    frame: 'referral-wings',
    pin: 'referral-scout',
    cosmetics: ['referral-scout', 'referral-wings'],
    plusDays: 0,
  },
  {
    count: 5,
    title: 'Команда',
    detail: 'Пин, рамка «Волна накама» и 7 дней Plus',
    frame: 'referral-tide',
    pin: 'referral-crew',
    cosmetics: ['referral-crew', 'referral-tide'],
    plusDays: 7,
  },
  {
    count: 10,
    title: 'Капитан',
    detail: 'Королевская рамка и пин-корона',
    frame: 'referral-master',
    pin: 'referral-master',
    cosmetics: ['referral-master', 'referral-master-pin'],
    plusDays: 0,
  },
  {
    count: 25,
    title: 'Легенда',
    detail: 'Тег, пин-феникс, огненная рамка и 30 дней Plus',
    frame: 'referral-phoenix',
    pin: 'referral-legend',
    cosmetics: ['animonster-legend', 'referral-legend', 'referral-phoenix'],
    plusDays: 30,
  },
] as const;
